-- 1. HelpGuides 테이블 생성
create table if not exists "HelpGuides" (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    page_id text not null, -- 예: 'profit_analysis'
    section_id text not null, -- 예: 'projected_profit'
    title text not null, -- 예: '예상 순수익'
    content text not null, -- 예: '계산 공식은...'
    icon_name text, -- 예: 'PieChart' (Lucide icon name)
    display_order integer default 0 -- 정렬 순서
);

-- 2. RLS(보안) 정책 설정
alter table "HelpGuides" enable row level security;

drop policy if exists "Enable read access for all users" on "HelpGuides";

create policy "Enable read access for all users"
on "HelpGuides" for select
using (true);

-- 3. 기존 데이터 초기화 (전체 삭제 후 재생성)
truncate table "HelpGuides";

-- 4. 각 페이지별 가이드 데이터 입력

-- [수익 분석 / Profit]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('profit_analysis', 'projected_profit', '예상 순수익이란?', '순수익은 총 매출에서 모든 비용을 뺀 실제 이익입니다.

• 계산식: 총 매출 - (총 변동비 + 총 고정비 + 재고 손실)
• 변동비: 재료비, 포장비 등 판매량에 따라 변하는 비용
• 고정비: 월세, 인건비 등 판매량과 무관한 비용

이 지표가 (+)여야 흑자 경영, (-)면 적자 상태입니다.', 'TrendingUp', 1),
('profit_analysis', 'goal_reverse', '목표 매출 역산', '사장님이 설정한 목표 금액을 벌려면, 메뉴를 몇 개나 팔아야 할까요?

현재 매장의 "판매 비중(어떤 메뉴가 잘 팔리는지)"을 분석하여, 목표 달성에 필요한 구체적인 판매 개수를 역으로 계산해 드립니다.

예: "월 1,000만 원을 벌려면 아메리카노 500잔, 라떼 300잔이 필요합니다."', 'Target', 2),
('profit_analysis', 'bep_analysis', '손익분기점 (BEP)', '적자를 면하기 위해 최소한 벌어야 하는 매출액입니다.

• 고정비가 높을수록 손익분기점은 높아집니다.
• 마진율이 좋은 상품을 많이 팔수록 손익분기점은 빨리 달성됩니다.

그래프의 막대가 이 지점을 넘겼는지 매일 확인하세요!', 'Scale', 3),
('profit_analysis', 'price_simulation', '가격 조정 시뮬레이션', '만약 전 메뉴의 가격을 5% 올리면 순수익은 얼마나 늘어날까요?

슬라이더를 움직여 가격 변동 시나리오를 미리 테스트해 볼 수 있습니다. 원가 상승이나 가격 인상 결정을 내리기 전에 시뮬레이션을 돌려보세요.', 'DollarSign', 4);

-- [대시보드 / Dashboard]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('dashboard', 'overview', '매출 현황 요약', '매장의 현재 상태를 한눈에 파악하는 화면입니다.

• 판매 제품: 현재 등록된 판매 가능한 메뉴 수
• 진행 중인 주문: 아직 처리가 완료되지 않은 신규/확인 중 주문 수
• 실시간 이익 분석: 원가 분석 페이지로 이동합니다.

데이터는 실시간으로 집계되므로, 주문이 들어오면 숫자가 즉시 변경됩니다.', 'LayoutDashboard', 1),
('dashboard', 'notice', '공지사항', '시스템 업데이트 내역이나 본사의 중요 알림이 표시되는 공간입니다.', 'Info', 2);

-- [품목 관리 / Items]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('items', 'item_types', '품목 유형 이해하기', '정확한 원가 계산을 위해 유형을 올바르게 선택해주세요.

• 제품(Product): 고객에게 판매하는 최종 메뉴 (예: 김치찌개, 아메리카노)
• 재료(Material): 메뉴를 만드는 데 쓰이는 재료 (예: 김치, 원두, 우유)
• 반제품(Component): 매장에서 직접 만들어 쓰는 중간 재료 (예: 특제 소스, 수제 시럽)', 'Box', 1),
('items', 'cost_management', '원가 갱신', '시장 가격 변동으로 재료비가 올랐다면, 여기서 "매입 단가"를 수정하세요.
연결된 모든 재료 리스트와 수익 분석 데이터가 자동으로 재계산되어 정확한 마진율을 보여줍니다.', 'RefreshCw', 2);

-- [주문 관리 / Orders]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('orders', 'order_flow', '주문 처리 과정', '주문 관리는 크게 두 가지 탭으로 나뉩니다.

1. [미완료 주문] 탭: 현재 처리 중인 주문이 표시됩니다.
2. [처리완료/취소] 탭: 완료되거나 취소된 지난 주문 내역이 보관됩니다.

각 주문 카드를 클릭하면 상세 내역(주문 메뉴, 요청 사항)을 볼 수 있습니다.', 'ShoppingCart', 1),
('orders', 'status_update', '상태 변경', '주문 상태를 변경하여 고객과 주방에 진행 상황을 공유하세요.

• 신규 → 확인: 주문 확인 또는 제작 시작
• 확인 → 완료: 조리 완료 및 서빙/배달

"완료" 처리된 주문만 최종 매출로 집계됩니다.', 'CheckCircle2', 2);

-- [지출 관리 / Expenses]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('expenses', 'record', '꼼꼼한 지출 기록', '정확한 순수익 계산을 위해서는 단 10원의 지출도 누락하지 않는 것이 중요합니다.

• 재료 사입비
• 배달 대행료
• 포장 용기 구매비
• 월세 및 공과금

영수증을 받는 즉시 이곳에 입력하는 습관을 들여보세요.', 'CreditCard', 1),
('expenses', 'fixed_variable', '고정비와 변동비', '지출을 입력할 때 성격을 구분하면 분석이 더 정교해집니다.

• 고정비: 매출이 0원이어도 나가는 돈 (월세, 정수기 렌탈비, 인터넷 요금)
• 변동비: 매출이 늘어나면 같이 늘어나는 돈 (수도광열비 일부, 재료비, 소모품비)'
, 'Scale', 2);

-- [재고 관리 / InventoryCheck]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('inventory_check', 'stock_taking', '재고 관리란?', '전산상의 재고 수량과 실제 창고에 있는 수량을 맞춰보는 작업입니다.

재료 리스트로 제품을 만들어도 로스(버리는 재료, 정량 초과 사용 등)는 반드시 발생합니다. 실사를 통해 이 "숨은 손실"을 찾아내야 정확한 원가 관리가 가능합니다.', 'ClipboardCheck', 1),
('inventory_check', 'process', '실사 진행 방법', '1. 주요 재료들의 실제 수량을 세어 입력합니다.
2. 시스템이 전산 재고와의 "차이(Loss)"를 계산합니다.
3. [실사 확정 및 비용 처리]을 누르면 차이만큼이 "비용"으로 처리되고, 재고 수량이 실제와 같게 조정됩니다.', 'Save', 2);

-- [환경 설정 / Config]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('config', 'design', '주문서 디자인', '고객이 보는 온라인 주문서 화면을 직접 꾸밀 수 있습니다.

• 상점 로고: 브랜드 이미지를 업로드하세요.
• 메인 배너: 먹음직스러운 음식 사진으로 식욕을 돋우세요.
• 안내 문구: 영업 시간, 원산지 표시 등 필수 정보를 적어주세요.', 'Palette', 1),
('config', 'form_elements', '입력 항목 설정', '주문 받을 때 필요한 정보를 자유롭게 추가하세요.

• 텍스트 입력: "알러지 정보", "현관 비밀번호" 등
• 선택 옵션: "포장/매장", "매운맛 단계" 등
• 드래그 앤 드롭으로 순서를 쉽게 바꿀 수 있습니다.', 'ListOrdered', 2);

-- [재료 관리 / BOMDetail]
insert into "HelpGuides" (page_id, section_id, title, content, icon_name, display_order) values
('bom_detail', 'importance', '재료 리스트의 중요성', '이 메뉴 하나를 팔 때마다 어떤 재료가 얼마나 줄어드는지 연결고리를 만드는 곳입니다.

이 연결이 되어 있어야 주문이 들어왔을 때 재고가 자동으로 차감되고, 정확한 마진율이 계산됩니다.', 'Link', 1),
('bom_detail', 'how_to', '작성 팁', '1. 왼쪽 검색창에서 들어가는 재료를 검색해 추가하세요.
2. 정확한 투입량(g, ml, ea)을 입력하세요.
3. "계산 원가"가 자동으로 합산되어 총 원가가 나옵니다.

재료가 빠진 게 없는지 우측 합계 금액을 보며 확인하세요.', 'Edit3', 2);
